### ISSUE TITLE
Volume increment/decrement

### ISSUE THREAD

**Issue by atom-smasher** [jpeddicord/speedofsound#27]
This is sort of a problem, sort of a feature request.

My primary use case is riding a bike, but this would apply just as much to other modes of transport.

Use case: I'm riding along with a friend at 20kph (in which case the app would set my volume to about 50%), and I have the volume manually turned down (to about 25%) from the automated settings so we can talk. If we slow down, the volume could actually increase abruptly; the opposite of what I want. OTOH, I'm riding at 20kph (again, the app would set my volume to about 50%) along a particularly loud road, in which case I might have the volume turned up (to about 75%) from the automated settings; when I speed up, the volume could actually decrease abruptly; again, the opposite of what I want.

The way to solve this: Instead of just converting speed into a percentage of full volume and making changes to the absolute volume level, the app should (ideally, perhaps as an optional mode) adjust the volume by incrementing and decrementing the volume. eg applying volume adjustments of "+1" or "-1", rather than setting volume level eg "25% of maximum" or "50% of maximum".

This would allow sensible volume adjustments in the two scenarios above, increasing the volume when I go faster and decreasing the volume when I go slower (ideally with configurable upper and lower "bounds" or "limits"; ie I don't want to mute the sound when I come to a stop, nor do I want to blow out my headphones/speakers/ears while going fast) while still allowing sensible use of manual volume adjustment.

**Comment by jpeddicord** [comment]
I agree this would be useful, though the implementation is somewhat difficult due to how volume controls work on Android. I suppose it might be able to override the volume buttons when active and do something like this, or sample your speed over time and let you adjust how fast it changes, instead of the speeds it changes at.

I currently don't have a ton of time for larger feature work, however, so this may not happen for a while. (Pull requests, if you're interested, are welcome though.)

**Comment by jpeddicord** [comment]
Android 8.0 makes this difficult to accomplish, due to the nature of how background services can (can't) function. I had to remove headset plug detection as well. ☹ Additionally, this project is largely in maintenance mode and this feature is unlikely to happen. If anyone is interested in working on this issue, feel free to comment and/or email me.

**Comment by Lee-Carre** [comment]
If Android requires that apps set loudness as absolute values (rather than relative like the OP requests), then make loudness changes conditional on the existing (or last set) value.

The desired goal, here, seems to be avoiding large changes in loudness. If so, there are surely several ways to achieve that.

Other sensible precautions (which might warrant their own ticket) include:
* when speed is below the configured minimum threshold, especially if starting ~0, then don't increase loudness if it's below the configured low-speed level
* for the OP's use-case, instead of adjusting loudness only based on speed, also (optionally) sample the microphone (if available) for ambient loudness; when the environment is quiet, then less of an increase is needed, when the environment is loud, more of an increase is needed
* ideally, make all of these variables tuneable by the user (hide them under some ‘advanced’ settings UI)

Since the OP's concern isn't resolved, this ticket should be reopened.
If closed for filtering purposes, then set a label instead.
